version: '3.5'
services:
  postgresserver:
    image: docker.io/library/postgres:alpine # podman
    #image: postgres:alpine # for docker
    container_name: hungry_guide_db
    hostname: postgres-server
    restart: always
    ports:
      - "10432:5432"
    environment:
      TZ: "Asia/Bangkok"
      POSTGRES_DB: hungry_guide_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGPORT: 5432
      POSTGRES_HOST_AUTH_METHOD: trust
    command:
      -c ssl=off
